import { Chivo } from "next/font/google";
import "./globals.css";
import BackToTopButton from "./_components/ScrollToTop";
import { Toaster } from "@/components/ui/toaster";

const chivo = Chivo({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-chivo",
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="en">
        <BackToTopButton />
        <body className={chivo.variable}>
          {children}
          <Toaster />
        </body>
      </html>
    </>
  );
}
